### ISSUE TITLE
Does not build on GHC-8.8.2

### ISSUE THREAD

**Issue by bergey** [morphismtech/free-categories#6]
I hope the fix is just moving parens, but I haven't tried.

Error:
```    Building library for free-categories-0.2.0.0..
    [1 of 4] Compiling Data.Quiver
    
    /private/var/folders/cn/qmlf53n918g_w0k87q4xx3rr0000gp/T/stack50980/free-categories-0.2.0.0/src/Data/Quiver.hs:139:19: error:
        • You can't specify an instance for a tuple constraint
        • In the quantified constraint ‘forall (x :: k) (y :: k).
                                        (Show (p x y), Show (q x y))’
          In the stand-alone deriving instance for
            ‘(forall x y. (Show (p x y), Show (q x y))) =>
             Show (ComposeQ p q x y)’
        |
    139 | deriving instance (forall x y. (Show (p x y), Show (q x y)))
```
